
extend type Query {
  author(id: String!): Author,
  authors: [Author!]!,
}

extend type Mutation {
  addAuthor(inp: AddAuthorInp!): Author @isKind(kind: LIBRARY_STAFF),
  removeAuthor(id: String!): String @isKind(kind: LIBRARY_STAFF),
  updateAuthor(inp: UpdateAuthorInp!): Author @isKind(kind: LIBRARY_STAFF),
}

type Author {
  id: String!,
  name: String!,
  books: [BookMetadata!]!,
}

input AddAuthorInp {
  name: String!,
}

input UpdateAuthorInp {
  id: String!,
  name: String,
}