
extend type Query {
  author(id: String!): Author,
  authors: [Author!]!,
}

extend type Mutation {
  addAuthor(inp: AddAuthor!): Author,
}

type Author {
  id: String!,
  name: String!,
  books: [BookMetadata!]!,
}

input AddAuthor {
  name: String!,
}