
extend type Query {
  bookMeta(id: String!): BookMetadata,
  bookMetas: [BookMetadata!]!,
}

extend type Mutation {
  createBookMeta(inp: CreateBookMetaInp!): BookMetadata @isKind(kind: LIBRARY_STAFF),
  removeBookMeta(id: String!): String @isKind(kind: LIBRARY_STAFF),
  updateBookMeta(inp: UpdateBookMetaInp!): BookMetadata @isKind(kind: LIBRARY_STAFF),
}

type BookMetadata {
  id: String!,
  name: String!,
  abstract: String!,
  ISBN: String!,
  authors: [Author!]!,
  publisherID: String!,
  publisher: Publisher!,
  books: [Book!]!,
}

input CreateBookMetaInp {
  name: String!,
  abstract: String!,
  ISBN: String!,
  authorIDs: [String!]!,
  publisherID: String!,
}

input UpdateBookMetaInp {
  id: String!,
  name: String,
  abstract: String,
  ISBN: String,
  publisherID: String,
}