
extend type Query {
  bookMeta(id: String!): BookMetadata,
  bookMetas: [BookMetadata!]!,
}

type BookMetadata {
  id: String!,
  name: String!,
  abstract: String!,
  ISBN: String!,
  authors: [Author!]!,
  publisherID: String!,
  publisher: Publisher!,
  books: [Book!]!,
}