
extend type Query {
  issueInfo(id: String!): IssueInfo,
  issueInfos: [IssueInfo!]!,
}

type IssueInfo {
  id: String!,
  status: IssueStatus!,
  bookID: String!,
  book: Book!,
  issuedByID: String!,
  issuedBy: User!,
  issueDate: Time!,
  returnDate: Time!,
  finePayment: Int!,
}

enum IssueStatus {
  BORROWED,
  RETURNED,
}