
extend type Query {
  issueInfo(id: String!): IssueInfo,
  issueInfos: [IssueInfo!]!,
}

extend type Mutation {
  issueBook(inp: IssueBook!): IssueInfo @isKind(kind: LIBRARY_STAFF),
  returnBook(inp: ReturnBook!): IssueInfo @isKind(kind: LIBRARY_STAFF),
  renewBook(inp: RenewBook!): IssueInfo @isKind(kind: LIBRARY_STAFF),
}

type IssueInfo {
  id: String!,
  status: IssueStatus!,
  bookID: String!,
  book: Book!,
  issuedByID: String!,
  issuedBy: User!,
  issueDate: Time!,
  returnDate: Time!,
}

enum IssueStatus {
  BORROWED,
  RETURNED,
}

input IssueBook {
  bookID: String!,
  issuedByID: String!,
  returnDate: Time!,
}

input ReturnBook {
  id: String!,
}

input RenewBook {
  id: String!,
  returnDate: Time!,
}