
extend type Query {
  publisher(id: String!): Publisher,
  publishers: [Publisher!]!,
}

extend type Mutation {
  addPublisher(inp: AddPublisherInp!): Publisher @isKind(kind: LIBRARY_STAFF),
  removePublisher(id: String!): String @isKind(kind: LIBRARY_STAFF),
  updatePublisher(inp: UpdatePublisherInp!): Publisher @isKind(kind: LIBRARY_STAFF),
}

type Publisher {
  id: String!,
  name: String!,
  books: [BookMetadata!]!,
}

input AddPublisherInp {
  name: String!,
}

input UpdatePublisherInp {
  id: String!,
  name: String,
}