
extend type Query {
  publisher(id: String!): Publisher,
  publishers: [Publisher!]!,
}

extend type Mutation {
  addPublisher(inp: AddPublisher!): Publisher,
}

type Publisher {
  id: String!,
  name: String!,
  books: [BookMetadata!]!,
}

input AddPublisher {
  name: String!,
}