
extend type Query {
  user(prn: String!): User,
  users: [User!]!,
}

extend type Mutation {
  resolveFine(prn: String!): User @isKind(kind: LIBRARY_STAFF),
}

type User {
  prn: String!,
  kind: UserKind!,
  name: String!,
  pendingFine: Int!,
  issuing: [IssueInfo!]!,
  allIssued: [IssueInfo!]!,
}

enum UserKind {
  STUDENT,
  FACULTY,
  LIBRARY_STAFF,
}