package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"

	"github.com/PICT-LibraryAutomation/granthpal/database/models"
	"github.com/PICT-LibraryAutomation/granthpal/graph"
	"github.com/PICT-LibraryAutomation/granthpal/utils"
)

// Books is the resolver for the books field.
func (r *authorResolver) Books(ctx context.Context, obj *graph.Author) ([]*graph.BookMetadata, error) {
	var books []models.BookMetadata
	err := r.DB.Model(&models.Author{}).Where("id = ?", obj.ID).Association("Books").Find(&books)
	if err != nil {
		return nil, err
	}

	return utils.Map(books, func(book models.BookMetadata) *graph.BookMetadata {
		return book.ToGraphModel()
	}), nil
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id string) (*graph.Author, error) {
	var author models.Author
	if err := r.DB.First(&author, "id = ?", id).Error; err != nil {
		return nil, err
	}

	return author.ToGraphModel(), nil
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context) ([]*graph.Author, error) {
	var authors []models.Author
	if err := r.DB.Find(&authors).Error; err != nil {
		return nil, err
	}

	return utils.Map(authors, func(author models.Author) *graph.Author {
		return author.ToGraphModel()
	}), nil
}

// Author returns graph.AuthorResolver implementation.
func (r *Resolver) Author() graph.AuthorResolver { return &authorResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type authorResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
