package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"fmt"

	"github.com/PICT-LibraryAutomation/granthpal/graph"
)

// IssueInfo is the resolver for the issueInfo field.
func (r *queryResolver) IssueInfo(ctx context.Context, id string) (*graph.IssueInfo, error) {
	panic(fmt.Errorf("not implemented: IssueInfo - issueInfo"))
}

// IssueInfos is the resolver for the issueInfos field.
func (r *queryResolver) IssueInfos(ctx context.Context) ([]*graph.IssueInfo, error) {
	panic(fmt.Errorf("not implemented: IssueInfos - issueInfos"))
}
