
export enum Errors {
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INVALID_DETAILS_PROVIDED = 'INVALID_DETAILS_PROVIDED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  ALREADY_AUTHENTICATED = 'ALREADY_AUTHENTICATED',
  USER_UNAUTHENTICATED = 'USER_UNAUTHENTICATED',
  NOT_ENOUGH_RIGHTS = 'NOT_ENOUGH_RIGHTS',
  BOOK_METADATA_DOESNT_EXIST = 'BOOK_METADATA_DOESNT_EXIST',
  BOOK_DOESNT_EXIST = 'BOOK_DOESNT_EXIST',
  USER_DOESNT_EXIST = 'USER_DOESNT_EXIST',
  ISSUE_INFO_DOESNT_EXIST = 'ISSUE_INFO_DOESNT_EXIST',
}